public class myVariablesExec 
{
	public static void my_id()
    {
        myVariables.myID();
        system.debug('myVariables class');
    }
    public static void my_Sobject()
    {
        myVariables.mySobjects();
        system.debug('myVariables class');
    }
    public static void my_Generic_Sobject()
    {
        myVariables.myGenericSobject();
        system.debug('myVariables class');
    }
}